-- 1) EXPLAIN PLAN

--- 1.1) 실행계획 확인 방법 1
---- 실제 데이터를 읽지 않는다. => I/O 정보에 무관하다.
EXPLAIN PLAN
SET STATEMENT_ID = 'TEST1' INTO PLAN_TABLE
FOR 
SELECT /*+USE_NL(E D)*/
   E.ENAME, E.DPTNO, D.DNAME
FROM EMP E, DPT D
WHERE E.DPTNO = D.DPTNO;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'TEST1', 'ALL'));

--- 1.1) 실행계획 확인 방법 2 
---- EXPLAIN PLAN 명령과는 달리, 한 번의 명령으로 여러개의 SQL에 대한 실행계획을 바로 볼 수 있음
---- 다양하게 옵션을 사용할 수 있어서 여러 가지의 정보를 선택적으로 확인할 수 있음
SET AUTOTRACE ON;

SELECT /*+USE_NL(e d)*/
  E.ENAME, E.DPTNO, D.DNAME
FROM EMP E, DPT D
WHERE E.DPTNO = D.DPTNO;

-------------------------------------------------------------------------------------------
-- 2) SET AUTOTRACE
--- 2.1) 명령의 옵션
SET AUTOTRACE ON EXPLAIN;
SET AUTOTRACE ON STATISTICS;
SET AUTOTRACE TRACEONLY;
SET AUTOTRACE TRACEONLY EXPLAIN;    -- DB 읽지 않기때문에 부하가 걸리지 않으면서도, 실행계획을 설명하는 방법이므로 추천.
SET AUTOTRACE TRACEONLY STATISTICS;
SET AUTOTRACE OFF;

-------------------------------------------------------------------------------------------

-- 3) 실행계획 분석
SET AUTOTRACE TRACEONLY EXPLAIN;
SELECT /*+USE_NL(e d)*/
  E.ENAME, E.DPTNO, D.DNAME
FROM EMP E, DPT D
WHERE E.DPTNO = D.DPTNO;



CREATE TABLE DPT (
  DPTNO NUMBER(3) PRIMARY KEY,
  DNAME VARCHAR2(14),
  LOC VARCHAR2(13)
);

CREATE TABLE EMP (
  EMPNO NUMBER(4) PRIMARY KEY,
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DPTNO NUMBER(3),
  CONSTRAINT EMP_DPT_FK FOREIGN KEY (DPTNO) REFERENCES DPT (DPTNO)
);

CREATE SEQUENCE EMP_SEQ
  START WITH 1000
  INCREMENT BY 1
  MAXVALUE 9999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE DPT_SEQ
  START WITH 100
  INCREMENT BY 10
  MAXVALUE 1000
  NOCACHE
  NOCYCLE;

INSERT INTO DPT(DPTNO, DNAME, LOC) VALUES (DPT_SEQ.NEXTVAL, 'MANAGE', 'DANGSAN');
INSERT INTO DPT(DPTNO, DNAME, LOC) VALUES (DPT_SEQ.NEXTVAL, 'ACCOUNT', 'YEOEEDO');
INSERT INTO DPT(DPTNO, DNAME, LOC) VALUES (DPT_SEQ.NEXTVAL, 'H/R', 'SUWON');


INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'KIM', 'SALESMAN', 7698, TO_DATE('12-03-2022', 'DD-MM-YYYY'), 1000, NULL, 100);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'LEE', 'MANAGER', 7839, TO_DATE('25-08-2022', 'DD-MM-YYYY'), 3000, 500, 120);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'PARK', 'ANALYST', 7566, TO_DATE('10-05-2023', 'DD-MM-YYYY'), 5000, NULL, 120);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'CHOI', 'CLERK', 7369, TO_DATE('03-01-2022', 'DD-MM-YYYY'), 800, NULL, 110);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'YOO', 'CLERK', 7369, TO_DATE('09-02-2022', 'DD-MM-YYYY'), 900, NULL, 110);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'KANG', 'SALESMAN', 7698, TO_DATE('14-06-2022', 'DD-MM-YYYY'), 1500, 300, 100);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'KIM', 'CLERK', 7782, TO_DATE('30-11-2022', 'DD-MM-YYYY'), 1200, NULL, 120);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'HWANG', 'SALESMAN', 7698, TO_DATE('17-07-2022', 'DD-MM-YYYY'), 1600, 500, 100);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'RYU', 'ANALYST', 7788, TO_DATE('02-09-2022', 'DD-MM-YYYY'), 4500, NULL, 120);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DPTNO) VALUES (EMP_SEQ.NEXTVAL, 'JUNG', 'MANAGER', 7839, TO_DATE('22-04-2022', 'DD-MM-YYYY'), 4000, NULL, 100);

